"""add tenant scheduling settings and business hours break

Revision ID: cabc09e41d68
Revises: d50352debdb9
Create Date: 2026-08-08 19:52:53.214392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cabc09e41d68'
down_revision: Union[str, None] = 'd50352debdb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_hours', sa.Column('break_start_time', sa.Time(), nullable=True))
    op.add_column('business_hours', sa.Column('break_end_time', sa.Time(), nullable=True))
    op.add_column(
        'tenants',
        sa.Column('min_advance_minutes', sa.Integer(), nullable=False, server_default='30'),
    )
    op.add_column(
        'tenants',
        sa.Column('max_advance_days', sa.SmallInteger(), nullable=False, server_default='60'),
    )
    op.add_column(
        'tenants',
        sa.Column('allow_cancellation', sa.Boolean(), nullable=False, server_default='true'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'allow_cancellation')
    op.drop_column('tenants', 'max_advance_days')
    op.drop_column('tenants', 'min_advance_minutes')
    op.drop_column('business_hours', 'break_end_time')
    op.drop_column('business_hours', 'break_start_time')
    # ### end Alembic commands ###
